### ISSUE TITLE
Is it possible to do the signal capturing on RaspberryPi?

### ISSUE THREAD

**Issue by thematrixdev** [akirjavainen/A-OK#3]
I don't have an Arduino on hand. Thanks.

**Comment by akirjavainen** [comment]
AFAIK it's not possible to accurately capture the timings with Pi GPIO. If anyone has a solution or if I'm just generally wrong here, please let me know. :)

**Comment by thematrixdev** [comment]
I have uploaded RemoteCapture.ino to Arduino. Pressing the "down" button on the remote control, the following is shown on "serial monitor".

> Successful capture, command is: 10100011101011101110000001011110000000010000000001000011001100001
Command repeated
Command repeated
Command repeated
Command repeated
Successful capture, command is: 10100011101011101110000001011110000000010000000000100100000100011
Command repeated
Command repeated
Command repeated
Command repeated
Bad capture, invalid command length 10
Bad capture, invalid command length 19
Bad capture, invalid command length 0
Bad capture, invalid command length 2
Bad capture, invalid command length 6
Bad capture, invalid command length 24
Bad capture, invalid command length 5
Bad capture, invalid command length 26
Bad capture, invalid command length 58
Bad capture, invalid command length 8

There are two commands captured. May I know which one is the useful one?

**Comment by akirjavainen** [comment]
The actual command is the first capture. There is an "after command" sent after each command. The meaning of that is yet to be figured, since it's not required by most motors.
