### ISSUE TITLE
New comand "change direction"

### ISSUE THREAD

**Issue by Privet-zdarova** [akirjavainen/A-OK#4]
hello @akirjavainen, i found another command "holding the STOP button for 5 seconds" ( its comand value is 80), this command is needed in a combination of changing the direction of the curtain movement, please add to the examples

 #define AOK_HOLDING_STOP  "10100011010001100101000000010110000000010000000001010000111111011"
I already tested it, it works!

**Comment by Privet-zdarova** [comment]
also add an example of checksum calculation to the description


Checksum: 8 bits unsigned, 8 bit sum of ID, Address, and Command. (for example: 
  "10100011   01000110 01010000 00010110        00000001 00000000      00100011    11010000   1" 
*Checksum = 01000110+01010000+00010110 + 00000001+00000000 + 00100011 + 11010000
*  if the final number turned out to be more than 8 bits, then only 8 least significant bits are used

**Comment by akirjavainen** [comment]
Thank you for this! I've included these in the latest commit.
