### ISSUE TITLE
It works on AC268-01 receiver with AC127 transmitter

### ISSUE THREAD

**Issue by brancooo1** [akirjavainen/A-OK#8]
Hi, thanks so much for the awesome work.

I used your findings to capture the codes from the A-OK AC127 to control the exterior blinds and it works! The blinds use the [AC268-01 Outdoor Venetian Blind Receiving Controller](https://www.a-okmotor.com/ac268-01-outdoor-venetian-blind-receiving-controller_p57.html). I think you can expand the list of tested devices :). Thanks again!

I will be preparing a Homebridge package for those who use iOS HomeKit for smarthome, it still needs testing and debugging but it will work!

![image](https://user-images.githubusercontent.com/15949818/214849593-602af592-c02e-4498-8225-7d5b933e7c12.png)
<img width="509" alt="image" src="https://user-images.githubusercontent.com/15949818/214849656-f2fcc6d1-68ac-4ed0-927e-7a1d391b51c2.png">

**Comment by akirjavainen** [comment]
Thank for testing and leaving a comment! You're very welcome. :)
